package com.zkd.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_system_user.id
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_system_user.user_id
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_system_user.user_psd
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    private String userPsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_system_user.user_name
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system_user
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    public User(Integer id, String userId, String userPsd, String userName) {
        this.id = id;
        this.userId = userId;
        this.userPsd = userPsd;
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system_user
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_system_user.id
     *
     * @return the value of tb_system_user.id
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_system_user.id
     *
     * @param id the value for tb_system_user.id
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_system_user.user_id
     *
     * @return the value of tb_system_user.user_id
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_system_user.user_id
     *
     * @param userId the value for tb_system_user.user_id
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_system_user.user_psd
     *
     * @return the value of tb_system_user.user_psd
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    public String getUserPsd() {
        return userPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_system_user.user_psd
     *
     * @param userPsd the value for tb_system_user.user_psd
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    public void setUserPsd(String userPsd) {
        this.userPsd = userPsd == null ? null : userPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_system_user.user_name
     *
     * @return the value of tb_system_user.user_name
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_system_user.user_name
     *
     * @param userName the value for tb_system_user.user_name
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}