package com.zkd.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrqc_user.ID
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrqc_user.STATUS
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrqc_user.USER_NO
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    private String userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrqc_user.LAST_LOGIN_DATE
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    private Date lastLoginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrqc_user.CREATE_USER
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrqc_user.CREATE_DATE
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrqc_user.UPDATE_DATE
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrqc_user.USER_PSD
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    private String userPsd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrqc_user
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public User(Integer id, Integer status, String userNo, Date lastLoginDate, String createUser, Date createDate, Date updateDate) {
        this.id = id;
        this.status = status;
        this.userNo = userNo;
        this.lastLoginDate = lastLoginDate;
        this.createUser = createUser;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrqc_user
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public User(Integer id, Integer status, String userNo, Date lastLoginDate, String createUser, Date createDate, Date updateDate, String userPsd) {
        this.id = id;
        this.status = status;
        this.userNo = userNo;
        this.lastLoginDate = lastLoginDate;
        this.createUser = createUser;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.userPsd = userPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrqc_user
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrqc_user.ID
     *
     * @return the value of qrqc_user.ID
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrqc_user.ID
     *
     * @param id the value for qrqc_user.ID
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrqc_user.STATUS
     *
     * @return the value of qrqc_user.STATUS
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrqc_user.STATUS
     *
     * @param status the value for qrqc_user.STATUS
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrqc_user.USER_NO
     *
     * @return the value of qrqc_user.USER_NO
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrqc_user.USER_NO
     *
     * @param userNo the value for qrqc_user.USER_NO
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrqc_user.LAST_LOGIN_DATE
     *
     * @return the value of qrqc_user.LAST_LOGIN_DATE
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrqc_user.LAST_LOGIN_DATE
     *
     * @param lastLoginDate the value for qrqc_user.LAST_LOGIN_DATE
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrqc_user.CREATE_USER
     *
     * @return the value of qrqc_user.CREATE_USER
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrqc_user.CREATE_USER
     *
     * @param createUser the value for qrqc_user.CREATE_USER
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrqc_user.CREATE_DATE
     *
     * @return the value of qrqc_user.CREATE_DATE
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrqc_user.CREATE_DATE
     *
     * @param createDate the value for qrqc_user.CREATE_DATE
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrqc_user.UPDATE_DATE
     *
     * @return the value of qrqc_user.UPDATE_DATE
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrqc_user.UPDATE_DATE
     *
     * @param updateDate the value for qrqc_user.UPDATE_DATE
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrqc_user.USER_PSD
     *
     * @return the value of qrqc_user.USER_PSD
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public String getUserPsd() {
        return userPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrqc_user.USER_PSD
     *
     * @param userPsd the value for qrqc_user.USER_PSD
     *
     * @mbg.generated Mon Aug 20 16:02:49 SGT 2018
     */
    public void setUserPsd(String userPsd) {
        this.userPsd = userPsd == null ? null : userPsd.trim();
    }
}