package com.zkd.dao.map;

import com.zkd.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system_user
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system_user
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system_user
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system_user
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system_user
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_system_user
     *
     * @mbg.generated Wed Jun 27 09:55:42 SGT 2018
     */
    int updateByPrimaryKey(User record);
}